---
name: Locale-Msgfmt
version: 0.06
author:
  - 'Ryan Niebur <ryanryan52@gmail.com>'
abstract: Compile .po files to .mo files
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
provides:
  Locale::Msgfmt:
    file: lib/Locale/Msgfmt.pm
    version: 0.06
  Locale::Msgfmt::Utils:
    file: lib/Locale/Msgfmt/Utils.pm
    version: 0.06
  Locale::Msgfmt::mo:
    file: lib/Locale/Msgfmt/mo.pm
    version: 0.06
  Locale::Msgfmt::po:
    file: lib/Locale/Msgfmt/po.pm
    version: 0.06
generated_by: Module::Build version 0.33
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
