---
name: Locale-Msgfmt
version: 0.14
author:
  - 'Ryan Niebur <ryanryan52@gmail.com>'
abstract: Compile .po files to .mo files
license: perl
resources:
  license: ~
build_requires:
  Test::More: 0
provides:
  Locale::Msgfmt:
    file: lib/Locale/Msgfmt.pm
    version: 0.14
  Locale::Msgfmt::Utils:
    file: lib/Locale/Msgfmt/Utils.pm
    version: 0.14
  Locale::Msgfmt::mo:
    file: lib/Locale/Msgfmt/mo.pm
    version: 0.14
  Locale::Msgfmt::po:
    file: lib/Locale/Msgfmt/po.pm
    version: 0.14
  Module::Install::Msgfmt:
    file: lib/Module/Install/Msgfmt.pm
    version: 0.14
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
